site_name: Htjozvh2  # نام سایت شما
site_url: https://ghasemnazemi-cmd.github.io/Htjozvh2/

theme:
  name: material
  language: fa  # برای راست‌چین شدن و زبان فارسی
  
  # --- اضافه کردن فاوآیکون در این قسمت ---
  favicon: assets/favicon.png
  logo: assets/favicon.png # اگر دوست دارید لوگوی بالای سایت هم همین باشد
  
  palette:
    # تنظیمات رنگ برای هماهنگی با آیکون جدید
    - scheme: default
      primary: deep orange
      accent: blue
    - scheme: slate
      primary: deep orange
      accent: blue

  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

# بخش‌های دیگر فایل شما (مثل nav) در ادامه قرار می‌گیرند
nav:
  - خانه: index.md

