site_name: Htjozvh2
site_url: https://ghasemnazemi-cmd.github.io/Htjozvh2/

theme:
  name: material
  language: fa
  direction: rtl
  # آدرس دقیق عکس در پوشه assets
  favicon: assets/favicon.png
  logo: assets/favicon.png
  
  palette:
    - scheme: default
      primary: deep orange
      accent: blue
    - scheme: slate
      primary: deep orange
      accent: blue

  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest

nav:
  - صفحه اصلی: index.md
